import lib

from lib import DimensionNameParser



def test_parse_dimension_names():
    processor = lib.DimensionNameParser.DimensionNameSorter()
    assert processor.get_dimension_name("12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("ITEM 12A 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("ITEM_12A 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("ITEM_12A_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("ITEM 12A_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("ITEM 12.1A 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("ITEM_12.1A 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("ITEM_12.1A_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("ITEM 12.1A_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("ITEM 12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("ITEM_12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("INSP 12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("INSP_12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("ITEM 12 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("ITEM_12 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("ITEM_12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("ITEM 12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("INSP 12 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("INSP_12 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("INSP_12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("INSP 12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("ITEM-12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("INSP-12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("ITEM 12.16", "INSP_") == "INSP_12.16"
    assert processor.get_dimension_name("ITEM_12.16", "INSP_") == "INSP_12.16"
    assert processor.get_dimension_name("INSP 12.16", "INSP_") == "INSP_12.16"
    assert processor.get_dimension_name("INSP_12.16", "INSP_") == "INSP_12.16"
    assert processor.get_dimension_name("ITEM-12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("INSP-12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("INSP-12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("INSP_12.1-1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("INSP-12.1-1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("ITEM-12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("ITEM_12.1-1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("ITEM-12.1-1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("12.1-1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("12.1-1", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("ITEM 12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("ITEM_12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("INSP 12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("INSP_12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("ITEM 12.1 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("ITEM_12.1 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("ITEM_12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("ITEM 12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("INSP 12.1 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("INSP_12.1 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("INSP_12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("INSP 12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("12.1 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("12.1 A", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("12.1_A", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("12 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("12 A", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("12_A", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("12A", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("INSP-12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("INSP_12-1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("INSP-12-1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("ITEM-12_10X", "INSP_") == "INSP_12J"
    assert processor.get_dimension_name("ITEM_12-1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("ITEM-12-1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("12-1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("12-1", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("12_1", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("12.1A", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("12.1_1", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("Aardvark", "INSP_") == "Aardvark"

    assert processor.get_dimension_name("#12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("#ITEM 12A 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM_12A 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM_12A_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM 12A_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM 12.1A 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#ITEM_12.1A 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#ITEM_12.1A_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#ITEM 12.1A_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("#ITEM 12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("#ITEM_12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("#INSP 12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("#INSP_12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("#ITEM 12 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM_12 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM_12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM 12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#INSP 12 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#INSP_12 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#INSP_12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#INSP 12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM-12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("#INSP-12", "INSP_") == "INSP_12"
    assert processor.get_dimension_name("#ITEM 12.16", "INSP_") == "INSP_12.16"
    assert processor.get_dimension_name("#ITEM_12.16", "INSP_") == "INSP_12.16"
    assert processor.get_dimension_name("#INSP 12.16", "INSP_") == "INSP_12.16"
    assert processor.get_dimension_name("#INSP_12.16", "INSP_") == "INSP_12.16"
    assert processor.get_dimension_name("#ITEM-12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("#INSP-12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("#INSP-12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#INSP_12.1-1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#INSP-12.1-1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#ITEM-12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#ITEM_12.1-1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#ITEM-12.1-1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#12.1-1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#12.1-1", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("#ITEM 12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("#ITEM_12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("#INSP 12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("#INSP_12.1", "INSP_") == "INSP_12.1"
    assert processor.get_dimension_name("#ITEM 12.1 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#ITEM_12.1 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#ITEM_12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#ITEM 12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#INSP 12.1 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#INSP_12.1 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#INSP_12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#INSP 12.1_10X", "INSP_") == "INSP_12.1J"
    assert processor.get_dimension_name("#12.1 1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#12.1_1X", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#12.1 A", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#12.1_A", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#12 1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#12 A", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#12_A", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#12A", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#INSP-12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#INSP_12-1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#INSP-12-1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM-12_1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM_12-1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#ITEM-12-1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#12-1X", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#12-1", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#12_1", "INSP_") == "INSP_12A"
    assert processor.get_dimension_name("#12.1A", "INSP_") == "INSP_12.1A"
    assert processor.get_dimension_name("#12.1_1", "INSP_") == "INSP_12.1A"

