from PyQt6 import QtCore, QtGui, QtWidgets


class gui_MicroVuProcessorMainWindow(object):
    def setupUi(self, MicroVuProcessorMainWindow):
        MicroVuProcessorMainWindow.setObjectName("MicroVuProcessorMainWindow")
        MicroVuProcessorMainWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MicroVuProcessorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 761, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtInputFolder = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.txtInputFolder.setObjectName("txtInputFolder")
        self.gridLayout.addWidget(self.txtInputFolder, 0, 2, 1, 1)
        self.btnSelectInputFolder = QtWidgets.QToolButton(parent=self.gridLayoutWidget)
        self.btnSelectInputFolder.setObjectName("btnSelectInputFolder")
        self.gridLayout.addWidget(self.btnSelectInputFolder, 0, 3, 1, 1)
        self.txtOutputFolder = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.txtOutputFolder.setObjectName("txtOutputFolder")
        self.txtOutputFolder.setReadOnly(True)
        self.txtInputFolder.setReadOnly(True)
        self.gridLayout.addWidget(self.txtOutputFolder, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.btnSelectOutputFolder = QtWidgets.QToolButton(parent=self.gridLayoutWidget)
        self.btnSelectOutputFolder.setObjectName("btnSelectOutputFolder")
        self.gridLayout.addWidget(self.btnSelectOutputFolder, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.txtInitials = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.txtInitials.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txtInitials.setObjectName("txtInitials")
        self.gridLayout.addWidget(self.txtInitials, 2, 2, 1, 1)
        self.OpNumberLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.OpNumberLabel.setObjectName("OpNumberLabel")
        self.gridLayout.addWidget(self.OpNumberLabel, 3, 0, 1, 1)
        self.txtOpNumber = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtOpNumber.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txtOpNumber.setObjectName("txtOpNumber")
        self.gridLayout.addWidget(self.txtOpNumber, 3, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 140, 600, 158))
        self.tableWidget.setMinimumSize(QtCore.QSize(600, 300))
        self.tableWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnWidth(0, 450)
        self.tableWidget.setColumnWidth(1, 100)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.btnProcessFiles = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnProcessFiles.setGeometry(QtCore.QRect(680, 450, 100, 23))
        self.btnProcessFiles.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnProcessFiles.setEnabled(False)
        self.btnProcessFiles.setObjectName("btnProcessFiles")
        MicroVuProcessorMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MicroVuProcessorMainWindow)
        self.statusbar.setObjectName("statusbar")
        MicroVuProcessorMainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MicroVuProcessorMainWindow)




    def retranslateUi(self, MicroVuProcessorMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MicroVuProcessorMainWindow.setWindowTitle(_translate("MicroVuProcessorMainWindow", "MicroVu 1Factory Processor"))
        self.btnSelectInputFolder.setText(_translate("MicroVuProcessorMainWindow", "..."))
        self.label.setText(_translate("MicroVuProcessorMainWindow", "Input Folder:  "))
        self.label_2.setText(_translate("MicroVuProcessorMainWindow", "Output Folder:  "))
        self.label_3.setText(_translate("MicroVuProcessorMainWindow", "Initials:  "))
        self.OpNumberLabel.setText(_translate("MicroVuProcessorMainWindow", "Op Number:"))
        self.btnSelectOutputFolder.setText(_translate("MicroVuProcessorMainWindow", "..."))
        self.btnProcessFiles.setText(_translate("MicroVuProcessorMainWindow", "Execute"))
        self.tableWidget.setVisible(False)
